/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#abd600",
        "on-surface-variant": "#444748",
        "cobalt-deep": "#4B00E0",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#474646",
        "on-tertiary-fixed": "#1c0062",
        "acid-glow": "#E2FF4D",
        "on-background": "#1b1c1c",
        "sabotage-crimson": "#FF2A3B",
        "canvas-light": "#FAFAFA",
        "surface-container": "#efeded",
        "primary-fixed": "#e5e2e1",
        "outline-variant": "#c4c7c7",
        "error-container": "#ffdad6",
        "signal-emerald": "#00FF85",
        "secondary-fixed": "#c3f400",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c1c",
        "secondary": "#506600",
        "inverse-surface": "#303031",
        "tertiary-fixed": "#e6deff",
        "hairline-dark": "#222222",
        "on-primary": "#ffffff",
        "primary": "#000000",
        "surface": "#fbf9f9",
        "acid-chartreuse": "#CCFF00",
        "surface-tint": "#5f5e5e",
        "on-secondary-fixed-variant": "#3c4d00",
        "surface-container-high": "#e9e8e7",
        "tertiary-fixed-dim": "#cabeff",
        "inverse-on-surface": "#f2f0f0",
        "tertiary-container": "#1c0062",
        "surface-subtle": "#F2F2F2",
        "surface-bright": "#fbf9f9",
        "on-tertiary-fixed-variant": "#4700d6",
        "on-tertiary": "#ffffff",
        "outline": "#747878",
        "surface-container-low": "#f5f3f3",
        "on-tertiary-container": "#876bff",
        "on-secondary-container": "#546b00",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "secondary-container": "#c1f100",
        "on-primary-fixed": "#1c1b1b",
        "inverse-primary": "#c9c6c5",
        "surface-variant": "#e3e2e2",
        "surface-dim": "#dbdad9",
        "background": "#fbf9f9",
        "on-secondary-fixed": "#161e00",
        "canvas-dark": "#050505",
        "on-error": "#ffffff",
        "surface-dark": "#111111",
        "primary-fixed-dim": "#c9c6c5",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e3e2e2",
        "hairline-light": "#E5E5E5",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        margin: "2rem",
        gutter: "1.5rem",
        "space-2xs": "0.25rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "gutter-sm": "0.75rem",
        "margin-mobile": "1rem",
        "space-xl": "3.5rem",
        "space-xs": "0.5rem",
        "space-lg": "2rem",
        "space-2xl": "5rem"
      },
      fontFamily: {
        "label-mono-sm": ["Space Mono", "monospace"],
        "display-hero-mobile": ["Space Grotesk", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "label-mono-lg": ["Space Mono", "monospace"],
        "label-pill": ["Work Sans", "sans-serif"],
        "body-base": ["Work Sans", "sans-serif"],
        "body-lead": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "label-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-hero-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-hero": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-xl": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-xl-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-mono-lg": ["14px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-pill": ["11px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-base": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lead": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
